dvanoni/notero

- .github/workflows/release.yml
- README.md
- package-lock.json
- package.json
Install [`standard-version`](https://github.com/conventional-changelog/standard-version) and update `README` with instructions for using it to release new versions.
Also clean up the `release` workflow.
> Set up standard-version

- README.md
- content/notion.ts
> Create new Notion page if previous page is not found

- README.md
- content/notero-item.ts
- content/notero.ts
- content/notion.ts
- typings/zotero.d.ts
Closes #7
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)
> Sync Zotero tags to Notion

- .eslintrc.json
- README.md
- content/notero-item.ts
- content/notion.ts
- typings/zotero.d.ts
Closes #11
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)
> Sync editors separately from authors

- README.md
- content/notero-item.ts
- content/notero.ts
- content/notion.ts
- typings/zotero.d.ts
Closes #9
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)
> Sync file path of best attachment to Notion

- package-lock.json
- package.json
Update `zotero-plugin` to version `1.0.64` which adds support for Zotero 6.
https://github.com/retorquere/zotero-plugin-webpack/compare/v1.0.62...v1.0.64
https://groups.google.com/g/zotero-dev/c/bh2zt1-aYec
> feat: Support installation in Zotero 6

- .gitignore
- README.md
- package-lock.json
- package.json
- profile.json.example
Update to the latest version of [zotero-plugin](https://github.com/retorquere/zotero-plugin) and update the local development instructions in the README.
> build: Update zotero-plugin to version 1.2.1

- .github/dependabot.yml
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates
> build: Enable Dependabot version updates

- README.md
> docs(README): Update "Development" section to describe new build process

- README.md
Address a question that has come up multiple times: #62 #66 #71 #72 #116 #193 #292
> docs(README): Add FAQ about invalid request URL

- src/content/sync/html-to-notion/__tests__/fixtures/formatting.html
- src/content/sync/html-to-notion/__tests__/fixtures/formatting.ts
- src/content/sync/html-to-notion/html-to-notion.ts
- src/content/sync/html-to-notion/parse-node.ts
> feat: Support inline math expressions in notes

- README.md
[Version 0.5.0](https://github.com/dvanoni/notero/releases/tag/v0.5.0) added support for automatically syncing notes, so let's describe how to use it!
Also tidy up some other parts of the README.
Closes #395
> docs(README): Describe how to use note syncing

- src/locale/zh-CN/notero.ftl
- src/locale/zh-CN/notero.properties
Updates from Crowdin project
https://crowdin.com/project/notero
> fix: Update translations for Simplified Chinese

- src/content/sync/__tests__/property-builder.spec.ts
- src/content/sync/property-builder.ts
- src/content/utils/__tests__/get-item-url.spec.ts
- src/content/utils/get-item-url.ts
- src/content/utils/index.ts
- types/zotero.d.ts
> fix: Convert item URLs to format that opens web library

- patches/@notionhq+client+2.2.14.patch
> build: Update patch for @notionhq/client 2.2.14

- .github/workflows/release.yml
- release-please-config.json
Configuring release-please for path: .
> chore: Bootstrap releases

- src/content/prefs/preferences.xhtml
- src/content/style/preferences.css
| Before | After |
| ![CleanShot 2024-08-23 at 23 13 36@2x](https://github.com/user-attachments/assets/a1fa3a69-ee8a-4ccb-ab87-87efef40d89a) | ![CleanShot 2024-08-23 at 23 08 16@2x](https://github.com/user-attachments/assets/00a0a41d-324e-4703-b99e-e308d6a85e2f) |
> fix(preferences): Fix height of sync configs table

- scripts/version.ts
Since the PRs generated by Release Please already bump the version number, we don't want to bump the version again when generating builds for those PRs. We look for branch names starting with `release-please` to identify those PRs.
> ci: Use current version as base for release PR builds

- .github/workflows/crowdin.yml
- crowdin.yml
- src/locale/en-US/notero.ftl
- src/locale/zh-CN/notero.ftl
Set up [Crowdin GitHub action](https://github.com/crowdin/github-action) using notero-bot for creating PRs.
Also update formatting of `.ftl` files so that Crowdin translations result in fewer diffs.
> ci: Use Crowdin GitHub action for updating translations

- src/content/prefs/preferences.tsx
- src/content/prefs/preferences.xhtml
- src/content/prefs/sync-configs-table.tsx
- src/content/services/preference-pane-manager.ts
- src/content/style/preferences.css
- src/locale/.zed/settings.json
- src/locale/en-US/notero.ftl
- src/locale/zh-CN/notero.ftl
- types/components/virtualized-table.d.ts
- types/l10n.d.ts
- types/xul.d.ts
- Notion token is now hidden by default, and visibility can be toggled via button
- Improved menu list handling
- Updated styles to match Zotero conventions
- Code cleanup
| Before | After |
| ![CleanShot 2024-09-09 at 23 33 56@2x](https://github.com/user-attachments/assets/5fcdb8e6-3027-424b-81b7-8d4211eb2b6d) | ![CleanShot 2024-09-09 at 23 34 18@2x](https://github.com/user-attachments/assets/078e6f9f-f31c-4914-9ae2-f733dc6d4a4b) |
> feat: Improve preferences UI

- README.md
Powered by https://github.com/dvanoni/notero-download
> docs(README): Add new link for directly downloading the latest release

- .github/workflows/release-commenter.yml
Using https://github.com/apexskier/github-release-commenter
> ci: Comment on issues and PRs when a fix is released for them

- eslint.config.mjs
- package-lock.json
- package.json
- src/content/utils/__tests__/get-item-url.spec.ts
- types/eslint-plugin-jest.d.ts
Install and configure [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) using `recommended` and `style` configs
> build: Enable Jest linting

- eslint.config.mjs
- package-lock.json
- package.json
Enable [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)
> build: Enable eslint-config-prettier
