dvanoni/notero

content/notero.ts
content/utils.ts

This should hopefully help with debugging in the future.
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

Ensure errors are logged regardless of if they have a stack

---

.eslintignore
.eslintrc.json
README.md
content/notero-item.ts
content/notero.ts
content/notion.ts
content/preferences.js
content/preferences.xul
content/types.ts
defaults/preferences/notero.js
locale/en-US/notero.dtd
package-lock.json
package.json
tsconfig.json
typings/zotero.d.ts

Add the option to sync items when modified. When saving to Notion, update exiting pages instead of creating duplicate pages.
In order for page updates to work properly, this requires a custom build of [notion-sdk-js](https://github.com/makenotion/notion-sdk-js) with a fix for the `method` passed to `fetch()`. (see https://github.com/dvanoni/notion-sdk-js/releases/tag/v0.4.12-dvanoni)
Closes #10

Sync items when modified and update existing Notion pages

---

README.md
content/notero-item.ts
content/notion.ts

Not sure I account all thing, but at least I've check it and it works

Add abstract field

---

README.md
content/notero-item.ts
content/notion.ts

* Followed same approach as https://github.com/dvanoni/notero/pull/35
* Tested locally and confirmed to be working
* Went with a text type for the date instead of a date type because Zotero itself doesn't store that property as a date
* For example, my test entries (journal articles) included dates of `2022-05`
* It makes the most sense for users to use a formula column on the Notion side to parse the date strings

Add support for Zotero's Date property

---

.github/dependabot.yml

Weekly checks were a bit too much, so I'm changing them to monthly.

build: Change Dependabot version update checks to monthly

---

README.md
src/content/collection-sync-config.ts
src/content/notero-item.ts
src/content/notero.ts
src/content/notion.ts
src/content/services/sync-manager.ts
typings/zotero.d.ts

Add support for syncing a multi-select `Collections` property to Notion. Each Zotero collection that an item is in is synced to Notion as a separate multi-select option.
For sub-collections, the option names are built the same way as on the Notero preferences screen using the `▸` character to concatenate sub-collection names.

feat: Sync `Collections` property to Notion

---

src/content/notero-item.ts
src/content/services/sync-manager.ts
src/content/utils/getAllCollectionItems.ts
src/content/utils/index.ts
typings/zotero.d.ts

Previously, pages in Notion would end up with old values for the `Collections` or `Tags` properties if changes (e.g. renames) were made directly to collections or tags in Zotero. To address this, we've added listeners for additional Zotero events so that we can sync items when associated collections or tags are modified, including when collections are moved.
This PR also adds the last sync time into the note of the Notion link attachment on synced items.

feat: Sync items when collections or tags are modified

---

README.md
package-lock.json
package.json
src/bootstrap.ts
src/content/constants.ts
src/content/notero.ts
src/content/services/event-manager.ts
src/content/services/index.ts
src/content/services/sync-manager.ts
src/content/services/ui-manager.ts
src/locale/en-US/notero.properties
src/locale/zh-CN/notero.properties
typings/zotero.d.ts

Add a "Sync to Notion" menu item to both the collection context menu and item context menu. When the collection menu item is selected, all items in the collection are synced. When the item menu item is selected, all selected items are synced.
- The menu item appears for all entries in the left sidebar, including those that are _not_ collections. This presents a confusing experience since selecting the menu item ends up doing nothing for entries that are not collections.

feat: Add sync button to context menus

---

src/content/services/ui-manager.ts
typings/zotero.d.ts

When selecting an item or items to sync from the context menu, ensure that only top-level items are requested to sync.

fix: Sync top-level items from context menu

---

README.md

Update the `Zotero URI` row in the README with a link to #172 so that folks know it doesn't work as expected.
Also remove the link to #30 now that it's completed.

docs(README): Add link to issue about broken Zotero URI links

---

patches/node-fetch+2.6.9.patch

I forgot to run `npx patch-package node-fetch` after `node-fetch` was updated in #247.

build: Update patch for `node-fetch` package

---

README.md

The previous link to the tutorial 'Using Notion and Zotero to build a literature tracker' was broken. Updated to the latest working link.

Updating the tutorial link

---

src/content/notion.ts
typings/zotero.d.ts

Add TypeScript type definitions for `Zotero.Date` based on https://github.com/zotero/utilities/blob/9e71e449b67e7e4a437f77d234613587b7c5d4c7/date.js

refactor: Add types for `Zotero.Date`

---

src/content/prefs/preferences.xhtml
src/content/services/preference-pane-manager.ts
src/locale/en-US/notero.ftl
src/locale/zh-CN/notero.dtd
src/locale/zh-CN/notero.ftl

Use [Fluent](https://projectfluent.org/) for localization in the Zotero 7 preference pane since [DTD support was removed](https://groups.google.com/g/zotero-dev/c/M_86IbuT8Nc).
Also localize the "sync notes" preference in Chinese since that wasn't included in #290.

feat: Localize Zotero 7 preference pane using Fluent

---

package.json

Enable the `xpi.supportsZotero7` property used by [zotero-plugin](https://github.com/dvanoni/zotero-plugin/blob/f4f6b7080ebe2979933b645c16e162a1f44141d5/bin/generate-update-manifest.ts#L42) to indicate support for Zotero 7 in `update.rdf`/`update.json`.

feat: Enable support for Zotero 7

---

.eslintrc.js
src/bootstrap.ts
src/content/notero-item.ts
src/content/prefs/sync-configs-table.tsx
src/content/services/chrome-manager.ts
src/content/services/event-manager.ts
src/content/services/sync-manager.ts
src/content/sync/html-to-notion/html-to-notion.ts
src/content/sync/sync-note.ts
src/content/utils/getDOMParser.ts
src/content/utils/getLocalizedString.ts
tsconfig.json
types/components/virtualized-table.d.ts

Enable the `strict-type-checked` ESLint rules [provided by v6 of `typescript-eslint`](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#reworked-configuration-names).
Also enable the [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) option in `tsconfig.json` so that indexing arrays or objects will include `undefined` in the type.

refactor: Enable stricter type checking

---

src/content/sync/html-to-notion/__tests__/annotations.spec.ts
src/content/sync/html-to-notion/__tests__/fixtures/annotations.html
src/content/sync/html-to-notion/__tests__/fixtures/annotations.ts
src/content/sync/html-to-notion/__tests__/fixtures/index.ts
src/content/sync/html-to-notion/annotations.ts

Syncing Zotero notes previously only supported highlight colors that were exactly those used in Zotero. As mentioned in https://github.com/dvanoni/notero/issues/4#issuecomment-1661322835, this meant that highlights from applications other than Zotero would most likely use different colors and thus not sync correctly into Notion.
This PR updates the color detection so that, instead of looking for an exact match with Zotero colors, the closest matching color is used. The color matching uses the ["redmean"](https://en.wikipedia.org/wiki/Color_difference) approach to best approximate a perceptually-closest color.

feat: Support note highlight colors other than Zotero's

---

package-lock.json
package.json

Fixes #314, fixes #315
As reported in #314 and #315, the release of [v0.4.10](https://github.com/dvanoni/notero/releases/tag/v0.4.10) broke Notero for users on Zotero 6 such that it was no longer usable at all.
Investigating the issue uncovered the offending error:
> global2[CONSTRUCTOR] is undefined
with partial stack trace:
> node_modules/core-js/internals/entry-unbind.js/module.exports -> /build/content/notero.js:3489:9
> node_modules/core-js/es/string/trim-end.js -> /build/content/notero.js:3500:24
> __require -> /build/content/notero.js:20:20
<details>
<summary>The relevant code from the bundled <code>notero.js</code> in v0.4.10 is as follows:</summary>
```js
// node_modules/core-js/internals/global.js
var require_global = __commonJS({ …
```

fix: Downgrade `core-js` to v3.31.1 to fix issue with `use strict`

---

src/bootstrap.ts

The default value for the [@typescript-eslint/ban-ts-comment](https://typescript-eslint.io/rules/ban-ts-comment/) rule sets `ts-expect-error` to `allow-with-description`, meaning that `@ts-expect-error` comments are allowed if they have a description following the directive.
So, this PR adds descriptions to the two `@ts-expect-error` comments in the code base, enabling us to remove a couple `eslint-disable-next-line` comments. ⭐

refactor: Improve usage of `@ts-expect-error`

---

.github/dependabot.yml

Use the Dependabot [`groups`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) configuration option to group together minor and patch version upgrades for development dependencies.

build(dependabot): Group dev dependency upgrades together

---

.github/dependabot.yml

Exclude `esbuild` from the Dependabot `dev-dependencies` group because it's on pre-1.0 versions—meaning a **minor** version bump is actually a **major** version bump.

build(dependabot): Exclude esbuild from dev-dependencies group

---

.github/dependabot.yml

With the current `groups` configuration, **minor/patch** version updates for dev dependencies are all included together in the `dev-dependencies` group, but **major** versions are not. Each dependency instead receives its own separate PR even if multiple updates should be included together—e.g. #358 and #360.
To prevent this issue, this PR creates groups for `commitlint`, `jest`, and `typescript-eslint`. It relies on the following property described in the [`groups` configuration](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) docs:
> Dependabot creates groups in the order they appear in your `dependabot.yml` file. If a dependency update could belong to more than one group, it is only assigned to the …

build(dependabot): Group dependency updates for related major versions

---

src/content/sync/notion-limits.ts
src/content/sync/notion-utils/build-rich-text.ts
src/content/sync/sync-note.ts

Notion imposes a [limit](https://developers.notion.com/reference/request-limits#limits-for-property-values) of 100 blocks per request. To comply with this limit, we now batch requests when creating notes so that they contain at most 100 blocks each.

fix: Batch note block requests to comply with Notion API limits

---

README.md
src/bootstrap.ts
src/content/prefs/notero-pref.ts
src/content/prefs/preferences.tsx
src/content/sync/__tests__/property-builder.spec.ts
src/content/sync/property-builder.ts
src/locale/en-US/notero.properties
src/locale/zh-CN/notero.properties
types/jsm.d.ts
types/xpcom.d.ts
types/xul.d.ts

The `citationKey` field from [Better BibTeX](https://retorque.re/zotero-better-bibtex/) can now:
- be synced as a **text** property named `Citation Key`
- be used as the title for Notion pages (via a new option named `Item Citation Key`)
The `Item Citation Key` option is only enabled if Better BibTeX is installed and enabled.
Closes #5, closes #254

feat: Support citation key property and page title format

---

src/content/sync/__tests__/property-builder.spec.ts
src/content/sync/property-builder.ts

Fix a bug that was introduced in #352 where whitespace is not preserved when building the property values to sync to Notion.
Fixes #401

fix: Preserve whitespace when building properties

---

src/content/sync/html-to-notion/__tests__/fixtures/index.ts
src/content/sync/html-to-notion/__tests__/fixtures/textOnly.html
src/content/sync/html-to-notion/__tests__/fixtures/textOnly.ts
src/content/sync/html-to-notion/__tests__/fixtures/withoutContainer.html
src/content/sync/html-to-notion/__tests__/fixtures/withoutContainer.ts
src/content/sync/html-to-notion/__tests__/html-to-notion.spec.ts
src/content/sync/html-to-notion/dom-utils.ts
src/content/sync/html-to-notion/parse-node.ts

Some notes generated by Zotero do not include the containing `<div data-schema-version="8">...</div>` element. This PR adds support for such notes.
Fixes #403

fix: Support parsing notes without container div

---

README.md
src/content/sync/property-builder.ts

Add support for syncing the following properties:
| Property Name | Property Type |
| `Date Modified`     | Date          |
| `Extra`             | Text          |
| `Place`             | Text          |
| `Proceedings Title` | Text          |
| `Publication`       | Text          |
| `Series Title`      | Text          |
Closes #49, closes #52, closes #65, closes #118, closes #214

feat: Add more properties that can be synced

---

.commitlintrc.json
.eslintignore
.prettierrc.json
README.md
package-lock.json
package.json
patches/@notionhq+client+2.2.13.patch
src/content/prefs/notero-pref.ts
src/content/prefs/preferences.tsx
src/content/prefs/preferences.xhtml
src/content/prefs/preferences.xul
src/content/style/preferences.css
src/content/sync/html-to-notion/html-to-notion.ts
src/content/sync/notion-client.ts
src/content/sync/notion-utils/index.ts
src/content/sync/notion-utils/is-full-database.ts
src/locale/en-US/notero.dtd
src/locale/en-US/notero.ftl
src/locale/zh-CN/notero.dtd
src/locale/zh-CN/notero.ftl
tsconfig.json
types/core-js-pure.d.ts
types/xul.d.ts

Replace the "Database ID" text field with a selection menu that lists the databases which Notero has access to. This enables directly selecting the desired Notion database instead of having to correctly obtain and paste the database ID. Trouble with this process has been the cause of at least 15 issues: #59 #60 #62 #71 #87 #116 #193 #217 #224 #249 #292 #349 #373 #380 #387
| Before | After |
| ![CleanShot 2023-12-31 at 17 54 35@2x](https://github.com/dvanoni/notero/assets/299357/f68e083a-183f-4587-a782-3d45c64c78b4) | ![CleanShot 2023-12-31 at 17 51 25@2x](https://github.com/dvanoni/notero/assets/299357/61665d95-281e-4a7a-9602-a763cb8e492f) |
The polyfill for `Object.fromEntries` used by `@notionhq/client` was not working in the Notero preferences window because the …

feat: Replace Notion database ID text field with selection menu

---

.github/workflows/build.yml
.github/workflows/release.yml

With #404, we no longer need to authenticate with the GitHub npm registry and thus can remove the permission for accessing it from CI.

ci: Remove unnecessary `packages: read` permission

---

.github/workflows/release.yml

Configure [release-please](https://github.com/google-github-actions/release-please-action) GitHub action for creating release PRs and GitHub releases.

ci: Configure release-please for GitHub releases

---

README.md
package-lock.json
package.json

Since `standard-version` has been [deprecated](https://github.com/conventional-changelog/standard-version/pull/907), we've configured `release-please` in #430 to replace it. This PR uninstalls `standard-version` and updates the README accordingly.

build: Remove `standard-version`

---

src/content/data/__tests__/item-data.spec.ts
src/content/notero.ts
src/content/prefs/notero-pref.ts
src/content/prefs/preferences.tsx
src/content/services/__tests__/sync-manager.spec.ts
src/content/services/__tests__/window-manager.spec.ts
src/content/services/index.ts
src/content/services/service.ts
src/content/services/sync-manager.ts
src/content/services/window-manager.ts
src/content/sync/__tests__/property-builder.spec.ts
src/content/sync/find-duplicates.ts
src/content/sync/notion-client.ts
src/content/sync/notion-types.ts
src/content/sync/property-builder.ts
src/content/sync/sync-job.ts
src/content/utils/__tests__/build-collection-full-name.spec.ts
src/content/utils/__tests__/get-item-url.spec.ts
src/content/utils/create-html-element.ts
src/content/utils/create-xul-element.ts
src/content/utils/elements.ts
src/content/utils/get-xul-element-by-id.ts
src/content/utils/index.ts
test/utils/index.ts
test/utils/window-mock.ts

Depending on the circumstances, Notero can sometimes end up creating duplicate Notion pages for a given Zotero item. To address this issue as requested in #252, this PR adds a utility function for finding duplicate pages based on a specific database property.
There is no UI created for this utility yet. This is a first iteration to test the efficacy of this approach based on user feedback.
The utility function can be called via the **Run JavaScript** window available from the menu: **Tools → Developer → Run JavaScript**.
Paste the following code into the window, ensure the "Run as async function" option is enabled, and click the **Run** button at the top left. This will return page titles that appear in the database multiple times.
```js
return await Zotero.Notero.findDuplicates();
```
To …

feat: Add utility for finding duplicate Notion pages

---

release-please-config.json
scripts/version.ts

- Disable [`include-component-in-tag`](https://github.com/googleapis/release-please/blob/f78f87b3ec986344c9265a9bd225b92a41aeac23/docs/manifest-releaser.md#subsequent-versions) option for Release Please so that it doesn't prefix releases with `notero`
- Update `version.ts` script so that it doesn't publish release artifacts with a prerelease version

ci: Fix release tagging and versioning

---

src/content/notero.ts
src/content/services/preference-pane-manager.ts
src/content/services/service.ts
src/content/services/sync-manager.ts
src/content/services/ui-manager.ts
types/zotero.d.ts

In Zotero 7 the preferences for Notero have moved into a pane in the main Zotero preferences window. However, as described in #395 and #432, this isn't clear at all.
To address this, we're restoring the **Notero Preferences...** item to the **Tools** menu in Zotero 7. Clicking it opens the Zotero preferences window and activates the Notero pane.
Closes #432

fix: Restore preferences menu item in Zotero 7

---

CHANGELOG.md

The link got messed up in #436 by my initial attempt at configuring Release Please

chore(CHANGELOG): Fix compare link for v0.5.8

---

CHANGELOG.md

[v5.0.0](https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v5.0.0) of `conventional-changelog-conventionalcommits` changed all version headings to use H2. Upon adopting Release Please, new updates to `CHANGELOG.md` started using this format. This PR updates the remaining version headings to match.
This change was generated with the following command:
npx conventional-changelog-cli -i CHANGELOG.md -s -p conventionalcommits -r 0
The updated header was copied from https://github.com/conventional-changelog/commitlint/blob/fb0b43c1138c4a7b4c3576ea6214452a337bc619/CHANGELOG.md.

chore(CHANGELOG): Use H2 for all version headings

---

package.json
scripts/generate-install-manifest.ts
scripts/install.rdf.pug

Require a minimum Zotero version of 6.0.27 and stop supporting Juris-M.
With #340 we started relying on the new `Zotero.getMainWindows()` function that was added to Zotero in zotero/zotero@fb148497ba8abc338e0916f33297330ce8657270 and released in version [6.0.27](https://github.com/zotero/zotero/releases/tag/6.0.27), meaning that Notero versions [0.4.13](https://github.com/dvanoni/notero/releases/tag/v0.4.13) and above require a minimum Zotero version of 6.0.27.
This change caused issues for users who were on newer versions of Notero but not Zotero, as described in these issues:
- https://github.com/dvanoni/notero/issues/147#issuecomment-1747527674
- #331
- #348
- #445

fix: Require minimum Zotero version 6.0.27

---

src/content/sync/progress-window.ts
src/content/sync/sync-job.ts
types/zotero.d.ts

To help with fixing sync errors, we now show the title of the item that is failing to sync.
Closes #377
| Before | After |
| ![CleanShot 2024-01-23 at 23 47 01@2x](https://github.com/dvanoni/notero/assets/299357/37c34051-ea15-4ee2-ade6-aa5e7839c58e) | ![CleanShot 2024-01-23 at 23 49 33@2x](https://github.com/dvanoni/notero/assets/299357/c3befd96-964b-4b20-ada6-63091cf5339b) |

feat: Show title of item when failing to sync

---

src/content/services/__tests__/sync-manager.spec.ts
src/content/services/sync-manager.ts
src/content/sync/sync-job.ts

Fixes #269
When the "sync when items are modified" option was enabled, Notero would only sync items when they were modified (`modify item` event) and _not_ when they were added to a collection (`add collection-item` event). This would usually work fine because when a user manually moves an item into a collection, it triggers both the `add collection-item` and `modify item` events.
However, when items are added via the Zotero Connector browser extension, the `modify item` event is _not_ triggered by default. It appears to only trigger if Zotero Connector imports additional info or a PDF for the item. If Zotero Connector does not import anything additional, then only the `add collection-item` event is triggered. This meant that such items would not automatically sync upon import.
To fix …

fix: Ensure newly-added items sync even if not modified

---

src/content/prefs/preferences.tsx
src/content/prefs/sync-configs-table.tsx

Fixes #412
In Zotero 7, the sync configs table would not render all items until it was scrolled. To resolve this, we now force the table to re-render once it becomes visible within the window (using [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)).
Somewhat inspired by [this fix in Zotero](https://github.com/zotero/zotero/blob/ee9e11a3ebd464f9482c27447c641692d9e2ea12/chrome/content/zotero/preferences/preferences_cite.jsx#L128).

fix: Fix sync configs table not rendering all items until scroll

---

src/content/sync/html-to-notion/__tests__/fixtures/index.ts
src/content/sync/html-to-notion/__tests__/fixtures/links.html
src/content/sync/html-to-notion/__tests__/fixtures/links.ts
src/content/sync/html-to-notion/parse-node.ts

Fixes #458
Notion only supports links that use the `http:` or `https:` protocol. This would cause an error when trying to sync notes with other types of links such as `zotero:`.
To resolve this, the `link` part of a rich text object is now only included if the link uses `http:` or `https:`.

fix: Only convert html links if they use http or https protocol

---

.github/workflows/build.yml

Made possible by https://github.com/actions/upload-artifact/pull/496
Replaces https://nightly.link

ci: Use new `artifact-url` output from `upload-artifact` build step

---

scripts/build.ts
src/shims/timer.ts

Shimming the timer functions in the `banner` content of the build bundle always felt pretty hacky. Now we use [`inject`](https://esbuild.github.io/api/#inject) to add the shims in a more structured manner.
This PR also remove the wrapping `if (!Zotero.Notero) { /* entire bundle here */ }` block which didn't seem necessary any more.

refactor: Use esbuild `inject` to shim timer functions

---

src/content/data/item-data.ts
src/content/sync/__tests__/sync-note.spec.ts
src/content/sync/sync-note.ts

As reported in #463, duplicate "Zotero Notes" blocks end up created when note content fails to sync. This occurred because block IDs were not saved into Zotero when a note failed to sync—even though the container blocks (i.e. "Zotero Notes" and the note heading) were indeed created in Notion. Without saving the block IDs into Zotero, the next sync attempt had nothing to reference and thus created additional container blocks.
We now save block IDs before attempting to sync the note content so that, if the note content fails to sync, we've already saved references to the block IDs to be used for the next sync attempt. Additionally, if we successfully create the "Zotero Notes" container but fail to create the note heading container, we still save the block ID of the "Zotero Notes" container.

fix: Avoid creating duplicate note blocks in Notion

---

README.md

Closes #470 
Add a badge and note indicating that Notero requires Zotero version 6.0.27 or above. The badge uses https://shields.io/badges/dynamic-json-badge to pull the `$.xpi.zoteroMinVersion` property from `package.json`.
Also update the badge for Buy Me a Coffee using the same dynamic badge approach. It pulls `$.data.public_supporters_count` from https://app.buymeacoffee.com/api/creators/slug/dvanoni.

docs(README): Note minimum required Zotero version

---

src/content/sync/notion-utils/__tests__/error.spec.ts
src/content/sync/notion-utils/error.ts
src/content/sync/notion-utils/index.ts
src/content/sync/sync-note.ts

When syncing notes into a container block that had been deleted, it appears the Notion API could return either a "not found" error or a validation error with a message about the block being "archived." This fix attempts to handle both cases whereas we previously only handled the "not found" case.

fix(notes): Improve handling of deleted note blocks

---

.github/workflows/release.yml

GitHub Actions has a [limitation](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) where a workflow run using the default `GITHUB_TOKEN` will not trigger further workflow runs. This was impacting the `release-please` job because the release PRs created by it would not trigger the `build` job. This unfortunately led me to disable the build check for PRs to `main`, which was not ideal.
Educated by [documentation for the create-pull-request action](https://github.com/peter-evans/create-pull-request/blob/ce008085c89860856de52c613ad894311f83c931/docs/concepts-guidelines.md#triggering-further-workflow-runs), I found a workaround for this using GitHub Apps and created the [Notero Bot](https://github.com/apps/notero-bot) app for this …

ci: Use GitHub App token to run `release-please` job

---

README.md
scripts/start.ts
zotero.config.example.json

It was recently [mentioned in the zotero-dev list](https://groups.google.com/g/zotero-dev/c/h4_UZDml-10/m/gDIzOtPkAAAJ) that the `-jsdebugger` flag can be passed when starting Zotero 7 to open the built-in developer tools, eliminating the need to have to connect from Firefox.
This PR updates the `start` script to use this `-jsdebugger` flag when starting Zotero 7 while maintaining the `-jsconsole` and `-debugger` flags for Zotero 6.
The `start` script also now provides a `ZOTERO_PID` environment variable to the `poststart` script which can be used for more effectively bringing Zotero to the foreground on macOS. `zotero.config.example.json` is updated to show how to use this.

build: Use built-in dev tools when starting Zotero 7

---

.husky/commit-msg

Husky [v9.1.1](https://github.com/typicode/husky/releases/tag/v9.1.1) added the ability to run npm package commands directly without using `npx`. So, this PR removes usage of `npx` from Husky hooks.

build: Remove `npx` from Husky hooks

---

src/content/sync/__tests__/property-builder.spec.ts
src/content/sync/property-builder.ts

Instead of using the APA style to generate author-date citation page titles, we now generate the citation by directly using a combination of the `firstCreator`, `displayTitle`, and `date` fields—inspired by the [`_buildBubbleString`](https://github.com/zotero/zotero/blob/181196149aea0b652ee938aaff7e1c0c217f0a2e/chrome/content/zotero/integration/quickFormat.js#L1070) function in Zotero.
This provides a couple benefits:
- We no longer require the APA style to be installed. This should hopefully resolve the `TypeError: style.getCiteProc is not a function` issue that many folks have reported.
- Closes #12
- Closes #543
- We now avoid the performance impact of generating citations with APA style. See more details in [this Zotero forum …

fix: Improve generation of author-date page titles

---

.github/workflows/release-commenter.yml

Using `skip-label` input from [github-release-commenter](https://github.com/apexskier/github-release-commenter)

ci: Skip release comments for PRs labeled `autorelease` or `maintenance`

---

.zed/tasks.json
src/content/data/__tests__/item-data.spec.ts
src/content/data/item-data.ts
src/content/errors/ItemSyncError.ts
src/content/errors/index.ts
src/content/prefs/preferences.tsx
src/content/sync/__tests__/sync-note-item.spec.ts
src/content/sync/__tests__/sync-regular-item.spec.ts
src/content/sync/notion-utils/index.ts
src/content/sync/notion-utils/normalize-id.ts
src/content/sync/property-builder.ts
src/content/sync/sync-job.ts
src/content/sync/sync-note-item.ts
src/content/sync/sync-regular-item.ts

Fixes #241 
Previously, changing the selected destination Notion database did not have the desired effect for items that had been synced to the previous database because Notero would continue to sync to the page in the previous database. To remedy this, we now do the following during the sync process:
- Recreate Notion pages when found in a different database
- Reset synced notes when page ID changes
This PR also includes a number of refactors. See the commits for details.

fix(sync): Support changing destination Notion database

---

src/content/services/__tests__/sync-manager.spec.ts
src/content/services/sync-manager.ts

Fixes #509
When note items were modified, they would be synced regardless of whether the "sync notes" option was enabled. This PR fixes that so that notes only sync:
- when "sync notes" is enabled and a note item is modified, or
- when a note item is specifically requested for sync via the context menu—regardless of the "sync notes" option

fix(sync): Do not sync note items when "sync notes" is disabled
